#created by 2018/5/9
#
#This is the dockerfile for oracle database 11g R2 Enterprise Edition
#
#THis is the dockerfile that was imitated from oracle/docker-images
#
#HOW TO BUILD THIS IMAGE
#	$ docker build -t oracle/database:11.2.0.4-ee .

FROM oraclelinux:7-slim

MAINTAINER Thygee

#安装目录可以自行创建及修改
#安装文件名称有可能需要自行修改
#安装软件可自行修改，但我已经写死在rsp中，也没必要修改
#安装库自行修改
#INSTALL_DB_SOFTWARE构建成镜像
ENV ORACLE_BASE=/opt/app/oracle \
	ORACLE_HOME=/opt/app/oracle/product/11.2.0/dbhome_1 \

	INSTALL_FILE_1="p13390677_112040_Linux-x86-64_1of7.zip"
	INSTALL_FILE_2="p13390677_112040_Linux-x86-64_2of7.zip"

	INSTALL_RSP="db_inst.rsp"

	INSTALL_DBCA_RSP="dbca.rsp"

	INSTALL_DB_SOFTWARE="install_db_software.sh"
	RUN_OR_INSTALL_ORACLE="run_or_install_oracle"

ENV INSTALL_DIR=$ORACLE_BASE/install \
    PATH=$ORACLE_HOME/bin:$ORACLE_HOME/OPatch/:/usr/sbin:$PATH \
    LD_LIBRARY_PATH=$ORACLE_HOME/lib:/usr/lib \
	CLASSPATH=$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib

#如果不存在会自动创建
COPY $INSTALL_FILE_1 $INSTALL_FILE_2 $INSTALL_RSP $INSTALL_DB_SOFTWARE $INSTALL_DIR/
#上面命令用来做镜像，下面命令是启动时执行的
COPY $INSTALL_DBCA_RSP $RUN_OR_INSTALL_ORACLE $ORACLE_BASE/

RUN chmod ug+x $INSTALL_DIR/*.sh && \
	chmod ug+x $ORACLE_BASE/*.sh && \
	sh $INSTALL_DIR/$INSTALL_DB_SOFTWARE

USER oracle
WORKDIR /home/oracle

VOLUME ["$ORACLE_BASE/oradata"]
EXPOSE 1521
#运行或安装，并检测信号机制优雅退出
CMD exec $ORACLE_BASE/$RUN_OR_INSTALL_ORACLE