#created by 2018/5/9
#
#This is the dockerfile for oracle database 11g R2 Enterprise Edition
#
#THis is the dockerfile that was imitated from oracle/docker-images
#
#HOW TO BUILD THIS IMAGE
#	$ docker build -t oracle/database:11.2.0.3-ee .

FROM oraclelinux:7-slim

MAINTAINER Thygee

#安装目录可以自行创建及修改
ENV ORACLE_BASE=/opt/oracle/app \
	ORACLE_HOME=/opt/oracle/app/product/11.2.0/dbhome_1 \

#安装文件名称有可能需要自行修改
	INSTALL_FILE_1="p13390677_112030_Linux-x86-64_1of7.zip"
	INSTALL_FILE_2="p13390677_112030_Linux-x86-64_2of7.zip"

#安装软件可自行修改
	INSTALL_RSP="db_inst.rsp"

#安装库自行修改
	INSTALL_DBCA_RSP=""